### ISSUE TITLE
Optimize query on BorReceiptLogs

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/bor#102]
PR #90 introduced BorReceiptLogs, which gives logs from state-sync as well. But, that introduced a delay in response time for the log filter query.

**Comment by Krishna-1604** [comment]
We are only getting that logs timeout related issue only when user doesn’t give startBlock and it starts fetching from 1st block, Right ?
Why don’t we put a check in GetLogs method that if the startBlock is not given in the request, Don’t include borLogs into that ? I know this is not a solution, But I found the code where we are fetching the logs and borLogs separately and then merging them, So just a thought.

@jdkanani @imyourm8

**Comment by Krishna-1604** [comment]
Or maybe we can add a boolean query param like `includeBorReceiptLogs` in which case the `startBlock` is compulsory and can't be  0. Again for this the developer must understand what the borReceiptLogs means what if he do he has the control over the data he want to request using that param. Also not sure if we can increase the timeout somehow using that param in this specific case.

**Comment by ssandeep** [comment]
Another thought - can we treat this as a general pagination problem and have a max limit of records that can be queried in a single call. So in this case, let's say we make start and end blocks mandatory and if the difference between start and end is more than 1000 or 10000, we don't allow such calls and throw an error with details about the max no of blocks that can be queried at once. Again, not sure if there would be impact on the consumption from devs or any other restrictions it might place for the use cases we are supporting.

**Comment by hellwolf** [comment]
This will force people using external RPC node service to setup their indexers such as thegraph early in their development cycle, even for a just small dapp.

Then what is the need of using that external RPC node at all after one already gone through setting up indexer? Almost none, since the rpc node wouldn't provide any ability to do "scalable range queries".

I found it perplexing that matic BOR node is eliminating the assumption that eth_getLogs should be scalable `O(log(N)` at least. And force people to use a indexing layer on top of it.

Please take this one seriously, it affects not only one team, I have validation that there are more teams affected by this.

**Comment by hellwolf** [comment]
> Or maybe we can add a boolean query param like `includeBorReceiptLogs` in which case the `startBlock` is compulsory and can't be 0. Again for this the developer must understand what the borReceiptLogs means but if he do he has control over the data he want to request using that param. Also not sure if we can increase the timeout somehow using that param in this specific case.

Something like this could work actually, since logs from "state-sync" might not be interesting to some teams.

**Comment by 0xKrishna** [comment]
Re-open if required.
