### ISSUE TITLE
#1107, #1085 PR missing due to revert

### ISSUE THREAD

**Issue by bbaktaeho** [maticnetwork/bor#1192]
#1107, #1085 PRs were included in v1.2.3, but they have all been removed in v1.2.8. It seems they were missing due to a revert that happened previously. Please verify.

**Comment by temaniarpit27** [comment]
Will check how they got removed in latest version but it will definitely be included in the upcoming version.
Thanks for bring this up

**Comment by bbaktaeho** [comment]
ok. thanks @temaniarpit27

**Comment by CitizenSearcher** [comment]
@temaniarpit27 PR https://github.com/maticnetwork/bor/pull/1109/files Is also missing. I believe this PR will have a very positive impact on small network reorgs: https://github.com/maticnetwork/bor/issues/1118

**Comment by temaniarpit27** [comment]
This is coming in next release

**Comment by manav2401** [comment]
Hey @bbaktaeho, I think these PRs never made it to any release (which is expected because we did a code freeze for the hard fork release and only included hot fixes in the subsequent releases). If you see [this line in v1.2.3](https://github.com/maticnetwork/bor/blob/v1.2.3/internal/ethapi/api.go#L705), it still has the older code. These changes will be included in upcoming release. Closing this for now, thanks!
