### ISSUE TITLE
How to use -dev with a genesis file OR how to mine without -dev ?

### ISSUE THREAD

**Issue by kopax** [maticnetwork/bor#1348]
Hi guys, I am just starting with bor and I would like to run a local dev server.

I am struggling to init the genesis block with `-dev` flag at the same time.

Without it, I am able to seed with a genesis file without issue, but then I cannot block.

I have been looking everywhere for some getting started developer documentation for contributors but I cannot find it.

Can you guys help me out understand how to get started ? 

Thanks and best :pray:

**Comment by manav2401** [comment]
Hey, ideally you should be able to run bor using `--dev` flag. Just note that it runs on clique consensus and not bor as in order to run inside bor consensus you'll need to setup some other components like heimdall for it to work. 

Can you try this?
```
git checkout develop
make bor
bor server --datadir ~/.bor/data --dev --dev.period 2
```

Let me know if you run into any issues. Thanks!

**Comment by Raneet10** [comment]
Hey @kopax were you able to run with the instructions provided ?

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kopax** [comment]
No I dot get how to mine without ĥeimdall  and --dev. What toml you use with that commands?

**Comment by kopax** [comment]
> to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

This guy seems to unanonymously want to hack me 😅

**Comment by manav2401** [comment]
@kopax, there isn't any extra configs. I am just running the command I mentioned above (the bor server one). 

Is you ask about starting a dev node with local heimdall? If yes, you'll require quite a few extra steps. 

Please checkout our testing tool (matic-cli), specifically [this](https://github.com/maticnetwork/matic-cli/?tab=readme-ov-file#matic-cli) section in order to spin a local node.

**Comment by manav2401** [comment]
Seems answered. Closing this for now, fee free to reopen if required.
