### ISSUE TITLE
The sequence of transactions with the same gas price is often not as expected

### ISSUE THREAD

**Issue by quchenhao** [maticnetwork/bor#154]
If I send two consecutive transactions with the same gas price, I expect the first transaction would be packed in front of the second transaction. I understand this is not 100% guaranteed in a blockchain. However, I expect a certain level of certainty can be achieved. But in matic, it is often not the case currently. I found a lot of transactions I sent are packed in the wrong order. I looked at the bor code and it seems the block producing code is sorting the transactions based on their arrival time as go-ethereum does. Therefore, I don't understand why it doesn't provide the same level of certainty of ordering as go-ethereum? On eth network, if I send two consecutive transactions with the same gas price, 80% to 90% they are packaged in the right order while in matic the order seems to be random.

**Comment by yoongyy** [comment]
I face another issue, similar to this. My node connected to 200 peers, however many of my transactions sent through my full node, at the end it is not found in the block chain. I am using at least 30GWei which is normal, but weird thing is sometime it is success and sometime it is missing with no error at all...

I am not sure is this the issue with my node or Polygon chain itself. But I have the same script running in BSC chain using the same machine has no this kind of issue.

The issue causing very hard to send the transaction to the chain because we do not know whether it is success or not.

**Comment by temaniarpit27** [comment]
Closing this as no updates on this
