### ISSUE TITLE
Why sum gasLimit of transactions always exceed the gasLimit in Block Header?

### ISSUE THREAD

**Issue by foxbupt** [maticnetwork/bor#499]
I was researched polygon network and read Bor source code recently. But when I compare the code and the real network, I had some questions:
1. Miner packages transactions in tx pool to seal block, it would check the gasLimit of transaction must lower than rest of block gas.
The logic code in core/state_transition.go:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/2442267/185587799-fc4646e5-7b87-42e9-9953-e6b771b8d0d9.png">

2. Worker generated the new block before seal block, the desiredLimit argument always pass w.config.GasCeil, it's 30000000.
In function CalcGasLimit, when parentGasLimit is lower than desiredLimit, the calculated limit value is always lower or equal to desiredLimit. So why there ares some block with gasLimit >= 30000000?
<img width="795" alt="image" src="https://user-images.githubusercontent.com/2442267/185590144-67c52526-5cf1-4329-a112-f034033c34ce.png">

3. In Worker commitTransactions function, it send recommitInterval message according to gas left ratio, the result to increase the recommitInterval fastly and complete the loop with reducer recommitInterval slowly.  The pending transaction is too many,  so the ratio always is 0.1?
 <img width="664" alt="image" src="https://user-images.githubusercontent.com/2442267/185590986-c8283202-1255-4c76-9263-f2fe46c14e9d.png">

Then I observed the mempool in blockchain, the recommitInterval always lower than 1000ms, except some block minted with 8 seconds, the recommitInterval would increased with 5000ms.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/2442267/185591525-4b5b85e7-ec5c-4b61-ae79-cf94a6c4a11e.png">

Thank you for your explanation, please!
-->

**Comment by 0xsharma** [comment]
#### To answer your queries :

- Incase the transaction utilises the entire gas limit, it will breach the block gas limit. Due to this we don’t allow transactions to get executed it their inclusion would breach the block gas limit.
- CalcGasLimit computes the gas limit of the next block after parent. It aims to keep the baseline gas close to the provided target, and increase it towards the target if the baseline gas is lower.
- We have deprecated using recommit as it required in networks with high block time, where it’s better to include new incoming high priced transactions in the high block time period. In low block times( 2sec) it is not required. Refer : https://github.com/maticnetwork/bor/pull/370

Closing for now, Re-open if you think this is still an issue. Thank you 💜
