### ISSUE TITLE
Supporting a "finalized" parameter for `eth_getBlockByNumber`

### ISSUE THREAD

**Issue by AaronKutch** [maticnetwork/bor#549]
Previously, our bridges used the "latest" parameter minus a set number of blocks in order to determine when a block could be relayed as unreorganizable. Since Eth 2.0 a "finalized" parameter has been supported by many chains, and we want to use more concrete proof-of-stake guarantees instead of probabilistic assumption guarantees. It appears that bor does not support this. Regardless if there is already some custom endpoint for this, could it also be exposed through the standard `eth_getBlockByNumber` so that we do not have to make bor-specific changes to our backend libraries?

**Comment by manav2401** [comment]
Hi @AaronKutch, even post ETH 2.0 merge, our finality does not change and still remains probabilistic. Well, technically as we're a geth fork, it would be easy to have the RPC endpoints catering / responding to the "finalized" parameter but we can't provide an explicit value for the same due to the probabilistic nature. For now, you'd need to use some safe block number (which is some fixed number behind the latest tip) as you do now. 

But, we're certainly working on some changes in the client and network, post which we'd be able to have support for these methods and give reliable output for the same. Moreover, I can't commit on some specific timeline for the same.  

Hope this helps. I'll keep this issue open for a while incase you've any additional questions.

**Comment by AaronKutch** [comment]
I didn't know it was probabilistic, we will keep our current setup then. How many blocks of delay should we have to make sure there is an astronomically low chance of reorganization? Our Eth 1.0 bridge used 35 blocks of delay for reference.

**Comment by manav2401** [comment]
35 blocks would be too low, at least for now. It would work in context of ETH 1.0 bridge as the block time was/is high there (13.5s pre-merge and 12s post merge). With a 2s block time on Polygon Mainnet, this number increases. I'd suggest to use a safe number of 200. 

Also, to be ultra safe, we send checkpoints every 512 blocks on ethereum. So that's an extremely high safe number.

**Comment by AaronKutch** [comment]
Thanks
