### ISSUE TITLE
Wrong author data from bor_getAuthor during chain reorg

### ISSUE THREAD

**Issue by chaoyandy** [maticnetwork/bor#582]
Hi,

We're experiencing the issue that author data returned from orphaned block during chain reorg. Though eventually the author data corrects by itself, but it is affecting the data correctness for live ingestion. What's worse, currently only `bor_getAuthor` API can return back author data,  but it's no where to tell which specific block(no block hash in both request/reply) it's associated to based on request param(`BlockNumber`) and return result(`Author` value). 

So in order to solve this, I found out a previous [commit](https://github.com/maticnetwork/bor/pull/435) that is adding correct miner address on API at RPC level but it's not been released yet. Is that possible to make this change into the next official build? Or will there be any other alternate solution? Thank you!

**Comment by 0xKrishna** [comment]
Yes this is a known issue, And we have already fixed that with the above mentioned commit.
It will be shipped with the next release for sure, Thanks for reporting.

Let me know if we can close this.

**Comment by chaoyandy** [comment]
Thank you! We can close this then, btw, when probably will be the next release?

**Comment by 0xKrishna** [comment]
Most probably in Dec OR Jan (Too many holidays in Dec).

**Comment by manav2401** [comment]
Hi @chaoyandy, so there has been some change with the PR you mentioned in your first comment (which adds miner field at rpc level). 

The change actually was supposed to go with an upcoming version but because the change is only on the RPC level, it breaks some downstream tooling applications which are relying on the equivalence of COINBASE opcode and response of the `eth_getBlock` endpoints. 

So, at the moment, this change has been reverted and won't be seen in upcoming releases. We'd be exploring other ways to achieve the same (as it would require consensus level changes) but I can't commit on any timeline for the same. 

We're also be exploring on the lines of what you suggested: adding some metadata in the `bor_getAuthor` endpoint like the block hash. This looks a doable addition and we'll surely think on this. Thanks for the suggestion. Are there any such more params (apart form block hash) which you think might be a good addition?

**Comment by chaoyandy** [comment]
Thanks @manav2401 ! This is understandable and appreciate the follow-up. 

I think `block_hash` would be sufficient if you could add to the response of `bor_getAuthor`. Another way to resolve this issue is adding an API `bor_getAuthorByBlockHash` so that we can call this new API instead. 

Could you provide some ticket/item that I can track for fixing this issue? Or we can simply use this one?

**Comment by chaoyandy** [comment]
Hello team/ @manav2401 , any updates on this?

**Comment by manav2401** [comment]
Hey @chaoyandy, we still have this task in our backlog as we were caught up with some high priority fixes/features post our v0.3.0 release. We'll use this issue for tracking once someone from the team starts implementing it. Thanks!

**Comment by chaoyandy** [comment]
> Hey @chaoyandy, we still have this task in our backlog as we were caught up with some high priority fixes/features post our v0.3.0 release. We'll use this issue for tracking once someone from the team starts implementing it. Thanks!

@manav2401 Thanks for the updates and appreciate the help! Is that possible for your team to bump the priority for this issue? It currently causes us to ingest lots of incorrect author data due to the increased reorgs and leads to more data quality issue across multiple Coinbase products. We really need to fix this as soon as we can. Thanks!

**Comment by Raneet10** [comment]
Hey @chaoyandy , I've raised the PR. So once this is merged and stowed in the next release, `bor_getAuthor` will also accept block hash. We decided not to return block hash along with the block author because modifying the return format may disrupt other downstream apps. Hope this'd resolve your concern. Thanks!

**Comment by chaoyandy** [comment]
> Hey @chaoyandy , I've raised the PR. So once this is merged and stowed in the next release, `bor_getAuthor` will also accept block hash. We decided not to return block hash along with the block author because modifying the return format may disrupt other downstream apps. Hope this'd resolve your concern. Thanks!

Great, that works! When'd be the next release?

**Comment by Raneet10** [comment]
Should be in a couple of weeks.

**Comment by chaoyandy** [comment]
Hi team @Raneet10 @manav2401 , I see there was a new release yesterday but did not include this fix, do we know when can we ship this one out? Thanks!
