### ISSUE TITLE
Opinion: Flags Merging is not a good idea IMO

### ISSUE THREAD

**Issue by maoueh** [maticnetwork/bor#616]
I would like to give my opinion on the flag renaming that happened on `0.3.1-beta` version, especially on those that are merged together in a single flag.

I'm of the opinion that those renaming causes more trouble then they are bringing values. Indeed, I imagine we are not alone, we manage `Geth` for different networks/forks of Ethereum. Diverging from "standard" `geth` flags brings more trouble than anything else. 

Before, we had more or less standardized deployment of Geth like instances but now the flag those flags will bring difference of `Polygon` version without much added value because as far as I can tell, behavior will be the same as before. I would be in favor of the change if it's was not for the fact that it now diverges from "standard" `geth` binaries

I just wanted to bring in my operator's opinion regarding that, feel free to close, I'll accept whatever is the final decision (but I would prefer if those changes would be reverted :D)

**Comment by 0xKrishna** [comment]
@pratikpatil024 @manav2401 @cffls

**Comment by cffls** [comment]
Hi @maoueh, thank you for your feedback. I've noticed that there are two instances where we've merged the address and port, one for GRPC and the other for metrics. Since GRPC is a new component, merging the address and port isn't a backward-incompatible change with Geth. Given that this release has already introduced many changes to existing flags and added new flags, I don't think it would be worth the effort to revert the metrics flags back to the Geth standard. In my opinion, maintaining consistency is only meaningful if BOR is fully compatible with the Geth CLI, which isn't the case in v0.3.0. Thank you again for sharing your thoughts and I appreciate your willingness to accept the final decision on this matter.

**Comment by maoueh** [comment]
> Since GRPC is a new component, merging the address and port isn't a backward-incompatible change with Geth

That a bit untrue as `--pprof.<xxx>` was existing before, so this is for me going away. This melding of `pprof` and `grpc` is super weird, but that's another subject.

> Given that this release has already introduced many changes to existing flags and added new flags

That's kind of at the heart of my rant, `bor server` for example is also a pain to handle for I'm not sure which benefit. `--networkid` and `--verbosity` flags behavior changes, for me it just creates changes for very little benefit (that might just be me).

It think ultimately it boils to having good reasons to make backward incompatible changes, for which my personal opinion on lots of those changes would have been to keep them like they were before.

Thanks
