### ISSUE TITLE
genesis-testnet-v4.json has issue

### ISSUE THREAD

**Issue by RajanHarshit** [maticnetwork/bor#635]
Hi team,

genesis file for testnet environment has issue while initializing bor container
getting an error `**Fatal: invalid genesis file: json: cannot unmarshal object into Go struct field BorConfig.config.bor.producerDelay of type uint64`**

below is genesis file link
https://raw.githubusercontent.com/maticnetwork/bor/master/builder/files/genesis-testnet-v4.json 

Solution should be
**"period": {
        "0": 2
      },
      "producerDelay": 6,
      "sprint": 64,
      "backupMultiplier": {
        "0": 2
      },**

**Note -**   _I've raised PR_ 
https://github.com/maticnetwork/bor/pull/636

**Comment by manav2401** [comment]
Hi, looks like you're using an older version of bor. I'd encourage you to use the latest v0.3.1-mumbai tag (See [this](https://forum.polygon.technology/t/bor-heimdall-mumbai-upgrade-v0-3-0-action-required/10560) and [this](https://forum.polygon.technology/t/bor-mumbai-upgrade-v0-3-1-mumbai-delhi-hardfork-action-required-revised/10629) for more info). 

The mumbai testnet recently went through a hard fork and hence the way fields are represented in the genesis file has been changed. It's now a map of block number to value instead of just a value. Hence, the fields in the file you mentioned are correct. Hope this answers your question. Thanks!
