### ISSUE TITLE
High disk usage

### ISSUE THREAD

**Issue by paymog** [maticnetwork/bor#940]
Our support team has aggregated some common issues and their solutions from past which are faced while running or interacting with a bor client. In order to prevent redundant efforts, we would encourage you to have a look at the [FAQ's section](https://wiki.polygon.technology/docs/faq/technical-faqs/) of our documentation mentioning the same, before filing an issue here. In case of additional support, you can also join our [discord](https://discord.com/invite/zdwkdvMNY2) server

#### **System information**

Bor client version: 0.4.0

OS & Version: Linux

Environment: Polygon Mainnet 

Type of node: Sentry

#### **Overview of the problem**

I'm finding that bor uses much more space than what's advertised [here](https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/#recommended-disk-size-guidance). It seems it should only use 6TB of space (which includes buffer) but my bor is currently using 7TB and isn't fully synced (I'm syncing from scratch). 

```
root@firehose-matic-reader-1-55bc6cbb4f-mz495:/data/firehose/reader/data# ls
bor  keystore
root@firehose-matic-reader-1-55bc6cbb4f-mz495:/data/firehose/reader/data# du -h -d 1
du: cannot access './bor/chaindata/105861355.ldb': No such file or directory
du: cannot access './bor/chaindata/105861359.ldb': No such file or directory
du: cannot access './bor/chaindata/105861378.ldb': No such file or directory
du: cannot access './bor/chaindata/105861461.ldb': No such file or directory
6.8T    ./bor
4.0K    ./keystore
6.8T    .
```

and when I look at the logs, it seems I'm at block 36764231.

#### **Reproduction Steps**

Not sure how to repro since this is happening during a full sync from scratch. Is it possible I'm missing some flags which do compaction/compression?

**Comment by manav2401** [comment]
Hi @paymog, can you confirm if you're syncing a full node or an archive node? If it's an archive node it is expected to take more size (and it will increase a lot much as you keep syncing). You might want to try running our network on [erigon client](https://github.com/ledgerwatch/erigon/) which takes much less space comparatively as compared to bor client. 

Also, if it's a full node, the size mentioned in the doc link you shared is correct. If you download the snapshot, that's the exact size it will consume. I believe your size might be high because you're syncing from scratch and hence there might be lot of unpruned state getting accumulated. You might want to try out pruning the state (which would take few hours) once you're done syncing. But depends on your end goal. If it's just running a bor node fully synced, I believe snapshot is the best way to go as it will get your node up and running till the tip of chain in less than a day.

**Comment by manav2401** [comment]
Seems answered, closing for now. Feel free to reopen.
