### ISSUE TITLE
Unable to retrieve transaction data using the `trace_transaction` API in for https://polygon-rpc.com

### ISSUE THREAD

**Issue by some-dev** [maticnetwork/bor#956]
I am encountering an issue while making batch requests to the Polygon RPC using the trace_transaction API. The API call is constructed as follows:
```

curl --location 'https://polygon-rpc.com' \
--header 'Content-Type: application/json' \
--data '[
  {
    "id": "tr-0x02675fad156af27c16950b7fc121c7af7233051a79cc5e3ced75d302a0e32fb8",
    "method": "trace_transaction",
    "params": [
      "0x02675fad156af27c16950b7fc121c7af7233051a79cc5e3ced75d302a0e32fb8"
    ],
    "jsonrpc": "2.0"
  }
]'

```

## Issue Details:

Inconsistent Response: The issue I'm facing is that the responses for these requests are not idempotent. Some of the requests return a proper transaction data result, while others return the following error:
```

[
    {
        "jsonrpc": "2.0",
        "id": "tr-0x02675fad156af27c16950b7fc121c7af7233051a79cc5e3ced75d302a0e32fb8",
        "error": {
            "code": -32601,
            "message": "the method trace_transaction does not exist/is not available"
        }
    }
]

```

I would like to inquire whether it is possible to enable the trace_transaction API for node. This would help in ensuring consistent retrieval of transaction data without encountering the "method not available" error.

**Comment by manav2401** [comment]
Hey, as it's a public RPC, it will not have `trace` calls exposed to public as they're resource intensive. You'll either need to run a node on your own on use a dedicated RPC from service providers (e.g. Infura, Alchemy, Ankr, quicknode, etc). 


Moreover, the actual call to trace transaction is a bit different. The call should be `debug_traceTransaction` instead of `trace_transaction`. Hence, when running your node, you'll have to enable the `debug` namespace by passing it in the `http.api` array. Once enabled, you can make debug queries to your node.

E.g.
```
curl http://localhost:8545 -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x4222747252f7fa58474cae45c57a6bdecc9fafd8e34f6b6d8860249883ebfd11"],"id":1}' -H "Content-Type: application/json"
{"jsonrpc":"2.0","id":1,"result":{"gas":21000,"failed":false,"returnValue":"","structLogs":[]}}
```

**Comment by manav2401** [comment]
Seems answered, closing for now. Feel free to reopen.
